apiVersion: v2
appVersion: 0.1.0
description: A Helm chart for an API Platform API
name: api
version: 0.1.0
home: https://api-platform.com
icon: https://api-platform.com/logo-250x250.png
dependencies:
    - name: postgresql
      version: ~9.3.2
      repository: https://charts.bitnami.com/bitnami/
      condition: postgresql.enabled
    - name: mercure
      version: ~3.0.0
      repository: https://kubernetes-charts.storage.googleapis.com/
      condition: mercure.enabled
