{{- $postgresqlServiceName := include "postgresql.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/part-of: {{ include "name" . }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s/%s?serverVersion=9.6" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword $postgresqlServiceName .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{ else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{ end }}
  secret: {{ .Values.php.secret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-secret: {{ .Values.php.mercure.jwtSecret | b64enc | quote }}
