version: '3.4'

x-cache-from:
  - &api-cache-from
    cache_from:
      - ${NGINX_IMAGE:?NGINX_IMAGE is not set or empty}
      - ${PHP_IMAGE:?PHP_IMAGE is not set or empty}
      - ${VARNISH_IMAGE:?VARNISH_IMAGE is not set or empty}

services:
  php:
    build:
      context: ./api
      target: api_platform_php
      <<: *api-cache-from
    image: ${PHP_IMAGE:?PHP_IMAGE is not set or empty}

  api:
    build:
      context: ./api
      target: api_platform_nginx
      <<: *api-cache-from
    image: ${NGINX_IMAGE:?NGINX_IMAGE is not set or empty}
    depends_on:
      - php

  cache-proxy:
    build:
      context: ./api
      target: api_platform_varnish
      <<: *api-cache-from
    image: ${VARNISH_IMAGE:?VARNISH_IMAGE is not set or empty}
    depends_on:
      - api

  client:
    # in production, we may want to use a static website hosting service
    # https://facebook.github.io/create-react-app/docs/deployment
    build:
      context: ./client
      target: api_platform_client_nginx
      args:
        - REACT_APP_API_ENTRYPOINT=${REACT_APP_API_ENTRYPOINT:?REACT_APP_API_ENTRYPOINT is not set or empty}
      cache_from:
        - ${CLIENT_IMAGE:?CLIENT_IMAGE is not set or empty}
    image: ${CLIENT_IMAGE:?CLIENT_IMAGE is not set or empty}

  admin:
    # in production, we may want to use a static website hosting service
    # https://facebook.github.io/create-react-app/docs/deployment
    build:
      context: ./admin
      target: api_platform_admin_nginx
      args:
        - REACT_APP_API_ENTRYPOINT=${REACT_APP_API_ENTRYPOINT:?REACT_APP_API_ENTRYPOINT is not set or empty}
      cache_from:
        - ${ADMIN_IMAGE:?ADMIN_IMAGE is not set or empty}
    image: ${ADMIN_IMAGE:?ADMIN_IMAGE is not set or empty}
