version: "3.4"

# Production environment override
services:
  php:
    build:
      context: ./api
      target: php_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  pwa:
     build:
      context: ./pwa
      target: prod

  caddy:
    build:
      context: ./api/
      target: caddy_prod
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
