api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    title: Hello API Platform
    version: 1.0.0
    # Enable the Varnish integration
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: ['%env(VARNISH_URL)%']
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']
        public: true
